version: '2'
services:
  cache:
    image: redis:2.8
    ports:
     - "6379:6379"
  dep-cache:
    image: dadarek/wait-for-dependencies
    links:
     - cache
    depends_on: 
     - cache
    command: cache:6379
